package com.sumi.transaku.core.domains;
// Generated May 29, 2016 4:58:28 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * User generated by hbm2java
 */
@Entity
public class StoreInventoryRestockHistory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	
	private int sellerId;
	private String itemCode;
	private double buyPrice;
	private double price;
	private double qty;
	private double totalBuyPrice;

	@JsonFormat(pattern="yyyy-MM-dd hh:mm:ss", timezone="Asia/Jakarta")
	private Date createdDate;
	
	public StoreInventoryRestockHistory() {
	}
	
	public StoreInventoryRestockHistory(int sellerId, String itemCode, double buyPrice, double price, double qty,
			double totalBuyPrice) {
		super();
		this.sellerId = sellerId;
		this.itemCode = itemCode;
		this.buyPrice = buyPrice;
		this.price = price;
		this.qty = qty;
		this.totalBuyPrice = totalBuyPrice;
	}



	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSellerId() {
		return sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public double getBuyPrice() {
		return buyPrice;
	}

	public void setBuyPrice(double buyPrice) {
		this.buyPrice = buyPrice;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public double getQty() {
		return qty;
	}

	public void setQty(double qty) {
		this.qty = qty;
	}

	public double getTotalBuyPrice() {
		return totalBuyPrice;
	}

	public void setTotalBuyPrice(double totalBuyPrice) {
		this.totalBuyPrice = totalBuyPrice;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}


}
