package com.sumi.transaku.core.domains;
// Generated May 29, 2016 4:58:28 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * User generated by hbm2java
 */
@Entity
public class SupplierInventory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	private String code;
	
	@ManyToOne
	@JoinColumn(name = "category_id")
	private InventoryCategory category;
	
	@ManyToOne
	@JoinColumn(name = "supplier_id")
//	@JsonIgnore
	private Supplier supplier;

	private String name;
	private String description;
	private double price;
	private double qty;

	@ManyToOne
	@JoinColumn(name = "qty_unit_id")
	private QtyUnit qtyUnit;
	
	private Double weight;

	@JsonFormat(pattern="yyyy-MM-dd", timezone="Asia/Jakarta")
	private Date createdDate;

	@JsonFormat(pattern="yyyy-MM-dd hh:mm:ss", timezone="Asia/Jakarta")
	private Date updatedDate;

	private String note;

	
	
	public SupplierInventory() {
	}
	public SupplierInventory(Integer id, String name, Supplier supplier) {
		super();
		this.id = id;
		this.supplier = supplier;
		this.name = name;
	}

	public SupplierInventory(String code, InventoryCategory category, Supplier supplier, String name,
			String description, double price, double qty, QtyUnit qtyUnit, Double weight, Date createdDate,
			String note) {
		super();
		this.code = code;
		this.category = category;
		this.supplier = supplier;
		this.name = name;
		this.description = description;
		this.price = price;
		this.qty = qty;
		this.qtyUnit = qtyUnit;
		this.weight = weight;
		this.createdDate = createdDate;
		this.note = note;
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public InventoryCategory getCategory() {
		return category;
	}

	public void setCategory(InventoryCategory category) {
		this.category = category;
	}

	public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public double getQty() {
		return qty;
	}

	public void setQty(double qty) {
		this.qty = qty;
	}

	public QtyUnit getQtyUnit() {
		return qtyUnit;
	}

	public void setQtyUnit(QtyUnit qtyUnit) {
		this.qtyUnit = qtyUnit;
	}

	public Double getWeight() {
		return weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	@Override
	public String toString() {
		return "SupplierInventory [id=" + id + ", code=" + code + ", category=" + category + ", supplier=" + supplier
				+ ", name=" + name + ", description=" + description + ", price=" + price + ", qty=" + qty + ", qtyUnit="
				+ qtyUnit + ", weight=" + weight + ", createdDate=" + createdDate + ", updatedDate=" + updatedDate
				+ ", note=" + note + "]";
	}

	

}
